### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/commbus#1]
Amended home page design

![1-home-page](https://user-images.githubusercontent.com/40568273/68662055-f596e780-0533-11ea-9741-7b6f5bcc4524.jpg)

[1-home-page.pdf](https://github.com/zeiq-co/commbus/files/3835502/1-home-page.pdf)

**Comment by kpierduta** [comment]
The client wants different logos on the client panel (that will feature on a few of the pages). 
They the logo to be in black and white and on hover roll into colour (like it works currently on the existing website - https://www.commbus.com/ (near bottom of page)

![1-heinz-bw](https://user-images.githubusercontent.com/40568273/67694521-5f8f8880-f99b-11e9-902a-c0a0c1276699.jpg)
![1-heinz-colour](https://user-images.githubusercontent.com/40568273/67694522-60281f00-f99b-11e9-9bcd-ac9fa5bae12b.jpg)
![2-asda-bw](https://user-images.githubusercontent.com/40568273/67694523-60281f00-f99b-11e9-9cac-a97545a78472.jpg)
![2-asda-colour](https://user-images.githubusercontent.com/40568273/67694524-60c0b580-f99b-11e9-84a0-68b5b819ee3e.jpg)
![3-itv-bw](https://user-images.githubusercontent.com/40568273/67694525-60c0b580-f99b-11e9-9ef9-0ca31fa96086.jpg)
![3-itv-colour](https://user-images.githubusercontent.com/40568273/67694527-60c0b580-f99b-11e9-80a2-fd4ca630c6d7.jpg)
![4-slimmingworld-bw](https://user-images.githubusercontent.com/40568273/67694528-60c0b580-f99b-11e9-840f-e2b634ea51b3.jpg)
![4-slimmingworld-colour](https://user-images.githubusercontent.com/40568273/67694530-61594c00-f99b-11e9-8ca4-b27a43c90138.jpg)
![5-anglia-ruskin-bw](https://user-images.githubusercontent.com/40568273/67694532-61594c00-f99b-11e9-960e-2c842ef60aff.jpg)
![5-anglia-ruskin-colour](https://user-images.githubusercontent.com/40568273/67694535-628a7900-f99b-11e9-8870-99db8c10fbba.jpg)
![6-sainsburys-bw](https://user-images.githubusercontent.com/40568273/67694537-628a7900-f99b-11e9-9807-6bb58d696ad0.jpg)
![6-sainsburys-colour](https://user-images.githubusercontent.com/40568273/67694538-628a7900-f99b-11e9-887f-149936e0cc52.jpg)
![7-fca-bw](https://user-images.githubusercontent.com/40568273/67695276-b184de00-f99c-11e9-90f0-2a299fc50447.jpg)
![7-fca-colour](https://user-images.githubusercontent.com/40568273/67695277-b184de00-f99c-11e9-8ab5-684314828397.jpg)
![8-staffssuni-bw](https://user-images.githubusercontent.com/40568273/67695278-b184de00-f99c-11e9-9bb9-9cab961ac2d0.jpg)
![8-staffsuni-colour](https://user-images.githubusercontent.com/40568273/67695279-b21d7480-f99c-11e9-8623-e1b7fd839cd7.jpg)
![9-breastcancancercare-bw](https://user-images.githubusercontent.com/40568273/67695281-b21d7480-f99c-11e9-89b9-a1d9212f612d.jpg)
![9-breastcancercare-colour](https://user-images.githubusercontent.com/40568273/67695282-b21d7480-f99c-11e9-833b-86a03aeed92e.jpg)
![10-gemalto-bw](https://user-images.githubusercontent.com/40568273/67695285-b2b60b00-f99c-11e9-93b4-7ea1be5727d0.jpg)
![10-gemalto-colour](https://user-images.githubusercontent.com/40568273/67695286-b2b60b00-f99c-11e9-80bd-eeaf17df6ce7.jpg)
![11-ukfast-bw](https://user-images.githubusercontent.com/40568273/67695287-b2b60b00-f99c-11e9-9caf-45f8c0397b2c.jpg)
![11-ukfast-colour](https://user-images.githubusercontent.com/40568273/67695290-b34ea180-f99c-11e9-8ae4-8a6e6c2a3d57.jpg)
![12-apprenticeships-bw](https://user-images.githubusercontent.com/40568273/67695292-b34ea180-f99c-11e9-91ab-8a8ebc358643.jpg)
![12-apprenticeships-colour](https://user-images.githubusercontent.com/40568273/67695294-b34ea180-f99c-11e9-8209-e95974454251.jpg)

**Comment by kpierduta** [comment]
@gagansaini1212  I will update this design so you have version with the correct header and footer on

**Comment by kpierduta** [comment]
@gagansaini1212 I have now updated this. You will notice the block styles repeat across pages consistently now so hopefully will make build more simple

**Comment by kpierduta** [comment]
@gagansaini1212 
thank you for the changes, more work is needed on the layout and sizing as everything is just very big at the moment and not in line. The colours aren't the same also. The fonts are BEBAS for titles and arial narrow with kerning at 30 for both fonts. I also made a note about the zoom effect on the projects on the front page - I only want image to zoom and not the writing - I want it to work as it does on this old Wordpress version I had started to put together: http://staging.commbus.com/

Also please refer to comment regarding rollover effect on client logos in earlier comment.
This is comparison of the design vs development. There is no rush to get back to me on this today or even this week, please take the time you need to get homepage together. The other pages should be more simple from there once we have formatting and blocks developed as per the design

Design on left - development so far on right
![homepage-comparison](https://user-images.githubusercontent.com/40568273/68671501-5845ae80-0547-11ea-9fe6-eccdc6534557.jpg)

**Comment by gagansaini1212** [comment]
@kpierduta can you please send me the client logo with a transparent background?

**Comment by kpierduta** [comment]
Hey @gagansaini1212  hope you are all good?
Here are the logos for you:

![client-logos_0000_apprenticeships-bw](https://user-images.githubusercontent.com/40568273/68748556-8fbe6480-05f4-11ea-9e3c-c0caf53a24f7.png)
![client-logos_0001_apprenticeships-colour](https://user-images.githubusercontent.com/40568273/68748558-8fbe6480-05f4-11ea-96a5-1adb8fb27020.png)
![client-logos_0002_ukfast-bw](https://user-images.githubusercontent.com/40568273/68748559-8fbe6480-05f4-11ea-8c2f-05b065971f27.png)
![client-logos_0003_ukfast-colour](https://user-images.githubusercontent.com/40568273/68748560-9056fb00-05f4-11ea-9aee-95c991540c96.png)
![client-logos_0004_gemalto-bw](https://user-images.githubusercontent.com/40568273/68748561-9056fb00-05f4-11ea-88b2-18fba68e6275.png)
![client-logos_0005_gemalto-colour](https://user-images.githubusercontent.com/40568273/68748563-9056fb00-05f4-11ea-969b-c842e1490494.png)
![client-logos_0006_Black- -White-3](https://user-images.githubusercontent.com/40568273/68748564-90ef9180-05f4-11ea-9447-c6f563d2c6f6.png)
![client-logos_0007_breastcancercare-colour](https://user-images.githubusercontent.com/40568273/68748565-90ef9180-05f4-11ea-9928-6b40745dd7fc.png)
![client-logos_0008_staffsuni-bw](https://user-images.githubusercontent.com/40568273/68748566-90ef9180-05f4-11ea-810a-1fd05f0b1ecf.png)
![client-logos_0009_staffsuni-bw](https://user-images.githubusercontent.com/40568273/68748569-91882800-05f4-11ea-91a0-66a9bc8dd5d8.png)
![client-logos_0010_fca-bw](https://user-images.githubusercontent.com/40568273/68748571-91882800-05f4-11ea-997f-0ea1aecd7d3c.png)
![client-logos_0011_fca-colour](https://user-images.githubusercontent.com/40568273/68748572-91882800-05f4-11ea-9278-05d683ce3f4d.png)
![client-logos_0012_sainsbury-bw](https://user-images.githubusercontent.com/40568273/68748573-91882800-05f4-11ea-9eb7-41949ac31084.png)
![client-logos_0013_sainsbury-colour](https://user-images.githubusercontent.com/40568273/68748574-9220be80-05f4-11ea-9362-05d5a693e23a.png)
![client-logos_0014_angliaruskin-bw](https://user-images.githubusercontent.com/40568273/68748575-9220be80-05f4-11ea-9114-5fd6a39e6bb1.png)
![client-logos_0015_angliaruskin-colour](https://user-images.githubusercontent.com/40568273/68748577-9220be80-05f4-11ea-8605-9e920d061348.png)
![client-logos_0016_slimmingworld-bw](https://user-images.githubusercontent.com/40568273/68748578-9220be80-05f4-11ea-8dd9-34a5c342a26f.png)
![client-logos_0017_slimmingworld-colour](https://user-images.githubusercontent.com/40568273/68748580-92b95500-05f4-11ea-9484-32ca6087f419.png)
![client-logos_0018_itv-bw](https://user-images.githubusercontent.com/40568273/68748581-92b95500-05f4-11ea-8c3c-82e217958b87.png)
![client-logos_0019_itv-colour](https://user-images.githubusercontent.com/40568273/68748582-92b95500-05f4-11ea-9500-ae80e0e3f0a7.png)
![client-logos_0020_Black- -White-2](https://user-images.githubusercontent.com/40568273/68748583-92b95500-05f4-11ea-8556-34c6d0a74a7d.png)
![client-logos_0021_asda-colour](https://user-images.githubusercontent.com/40568273/68748584-9351eb80-05f4-11ea-837c-006a144140f6.png)
![client-logos_0022_Black- -White-1](https://user-images.githubusercontent.com/40568273/68748585-9351eb80-05f4-11ea-8948-12800a51f85d.png)
![client-logos_0023_heinz-colour](https://user-images.githubusercontent.com/40568273/68748586-9351eb80-05f4-11ea-9bde-7ca97a129dcc.png)
