### ISSUE TITLE
Main page template

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/commbus#2]
This template will be used for the following pages:

Promotional buses (will have different content)
Event support

Can the header, contact form section in the bottom and the footer be taken from this template and be the same on each page, please.

![1-main-template-page-event-support](https://user-images.githubusercontent.com/40568273/68655343-c9756980-0527-11ea-9604-04e376d52a45.jpg)

**Comment by gagansaini1212** [comment]
@kpierduta what about commbus logo? It will be similar to this template or we will move with what we already have?

**Comment by kpierduta** [comment]
@gagansaini1212 
I have uploaded the latest design and this is the logo to use below - it's just their logo without the tagline now. I will also send over image assets shortly and icons

![commbus-official-logo-no-tagline](https://user-images.githubusercontent.com/40568273/68655447-f590ea80-0527-11ea-90c6-486aa5bf5bef.png)

**Comment by gagansaini1212** [comment]
@kpierduta I have committed the changes in this issue please check and give your valuable feedback.

**Comment by gagansaini1212** [comment]
@kpierduta Done with changes again. Please check. Now I am leaving. So will check in tomorrow and fix issues if any.

**Comment by kpierduta** [comment]
@gagansaini1212 what is the page url for this page, please?

**Comment by gagansaini1212** [comment]
@kpierduta This is our home page
