### ISSUE TITLE
Service boxes styling

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/commbus#23]
- [x] Make sure font is the same formatting (font size, line height, font-family) as other paragraphs on the website.

- [x] Give enough padding within the box so the elements sit in line and it has equal spaces at the top, sides and bottom.

<img width="1056" alt="Screenshot 2020-01-03 10 24 14" src="https://user-images.githubusercontent.com/40568273/71718525-5dbac900-2e13-11ea-82c0-2f6e383af844.png">

- [x] Make bullet points fit on one line

- [x] Remove 'bold' from font, so that writing is same format as other paragraphs

<img width="1177" alt="Screenshot 2020-01-03 10 26 43" src="https://user-images.githubusercontent.com/40568273/71718614-ad999000-2e13-11ea-8cb3-3ec86bc697fe.png">

**Comment by iamkunall** [comment]
@kpierduta  bullet points fit on one line is not possible.
