### ISSUE TITLE
Minor changes

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/commbus#37]
- [x] Add 3 x more space between different blocks on this page
<img width="1229" alt="Screenshot 2020-01-08 09 56 59" src="https://user-images.githubusercontent.com/40568273/71968668-473eb400-31fd-11ea-9605-4da628c02b37.png">

___

- [x] On bigger screens writing is overlapping image
![WhatsApp Image 2020-01-08 at 09 50 32](https://user-images.githubusercontent.com/40568273/71969274-3e021700-31fe-11ea-9033-2510a0895e73.jpeg)

![WhatsApp Image 2020-01-08 at 10 03 42](https://user-images.githubusercontent.com/40568273/71969276-3e021700-31fe-11ea-808c-4d0ba65acedd.jpeg)

___

- [x] Change testimonial design box - outline and shape to blue and add image circle

- [x] Information below testimonial all in Bebas font

<img width="482" alt="testimonial-box-design" src="https://user-images.githubusercontent.com/40568273/72341458-3e008c00-36c2-11ea-815d-f7eb9b86970b.png">

___

- [x] Can you make the images that are set under the client display block, vehicle images block and the individual images on the project page so that they are a pop up that shows the image bigger.

___

- [x] Change the ticks so that they are just bullet points that are the same size & colour of the text (too big at the moment)

<img width="69" alt="Screenshot 2020-01-14 11 44 35" src="https://user-images.githubusercontent.com/40568273/72341861-43aaa180-36c3-11ea-967d-b3f13053f609.png">

**Comment by iamkunall** [comment]
@kpierduta can you explain this point 
"Can you make the images that are set under the client display block, vehicle images block and the individual images on the project page so that they are a pop up that shows the image bigger."
