### ISSUE TITLE
Team pop up block design

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/commbus#38]
Here is the design for the pop up on the team page

![team-block-design](https://user-images.githubusercontent.com/40568273/72061060-01512100-32cd-11ea-9c01-f7ec6953a85d.png)

**Comment by kpierduta** [comment]
@iamkunall 

- [x] Photographs are distorted/squashed - is this circle image automatically pulled from image we pull from team page or do I need to upload new images in Contentful?

- [x] Name font weight is too big, font needs to be thinner weight

<img width="313" alt="Screenshot 2020-01-26 16 55 37" src="https://user-images.githubusercontent.com/40568273/73138621-b53c0580-405c-11ea-926c-94cfeac2ccdc.png">

**Comment by iamkunall** [comment]
@kpierduta   yes you need to upload new images in Contentful.
