### ISSUE TITLE
General changes (Website look & feel)

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/commbus#39]
- [x] Make Commbus logo bigger in top menu

- [x] Can we try Avenir Next Condensed font for paragraph text (keep Bebas for titles)

- [x] Change main menu font style to Bebas

- [x] Can the hover colour on the main menu change to Commbus blue (RGB(72, 124, 147))

- [x] Add social media icons to footer

- [x] Make changes to contact form box as per screenshot below

- [x] Change home icon to the one designed on Zeplin and make half the size

<img width="391" alt="Screenshot 2020-01-14 10 09 02" src="https://user-images.githubusercontent.com/40568273/72334846-e9571400-36b5-11ea-82e3-c4527a818135.png">

<img width="387" alt="Screenshot 2020-01-14 10 17 51" src="https://user-images.githubusercontent.com/40568273/72335609-253ea900-36b7-11ea-8707-ffdc0d1275b4.png">

- [x] Change 'Trusted by' to Bebas font in all instances

<img width="240" alt="Screenshot 2020-01-14 11 28 12" src="https://user-images.githubusercontent.com/40568273/72340978-1230d680-36c1-11ea-9cd9-2d42774bb2d6.png">

- [x] Make sure 'Trusted by' is lined up so begins where the title does above - see red line in screenshot.

![homepage-alignment](https://user-images.githubusercontent.com/40568273/72341120-63d96100-36c1-11ea-8134-09d7207fa788.png)

**Comment by iamkunall** [comment]
@kpierduta  can you explain what do you mean by "Change main menu font style to Bebas"

**Comment by iamkunall** [comment]
@kpierduta there is no social media icons in the footer

**Comment by kpierduta** [comment]
Bebas font thickness
- [x] Make weight thinner - all instances of Bebas need to have consistent thickness - below examples are too thick.

These in dropdown menus:
<img width="423" alt="Screenshot 2020-02-06 08 42 03" src="https://user-images.githubusercontent.com/40568273/73920037-92abb700-48bc-11ea-9374-9c19adc5f1e6.png">

These are titles of projects:
<img width="588" alt="Screenshot 2020-02-06 08 43 01" src="https://user-images.githubusercontent.com/40568273/73920130-b66efd00-48bc-11ea-8a67-9bf20f24ce14.png">


Please make client name level on both sides, regardless of how long testimonial is:
<img width="1071" alt="Screenshot 2020-02-06 08 43 31" src="https://user-images.githubusercontent.com/40568273/73920176-c850a000-48bc-11ea-9ef6-18b97e51104e.png">

Make sure line-height is equal across the site - bottom paragraph looks good, top paragraph looks cramped:
<img width="345" alt="Screenshot 2020-02-06 08 44 07" src="https://user-images.githubusercontent.com/40568273/73920231-e3bbab00-48bc-11ea-9236-26f95a45e4e1.png">

On blog page, there should be load more button (as per zeplin)
<img width="539" alt="Screenshot 2020-02-06 08 47 07" src="https://user-images.githubusercontent.com/40568273/73920537-7e1bee80-48bd-11ea-910e-9519507eba2a.png">

**Comment by kpierduta** [comment]
Contact page change

- [x] Make sure content starts at same level as title above - so padding to the left is the same

- [x] Reduce height of map by half and make sure it touches the top/bottom and right hand side of the page.

![contact-page-change](https://user-images.githubusercontent.com/40568273/73922552-431bba00-48c1-11ea-8d43-f659c35f28e5.jpg)

[contact-page-change.pdf](https://github.com/zeiq-co/commbus/files/4164186/contact-page-change.pdf)


Add Deckerdence call to action above the footer on the home page and the contact page only.

![deckerdence-cta-on-commbus-site](https://user-images.githubusercontent.com/40568273/73922646-6c3c4a80-48c1-11ea-8856-ee7a525103a4.jpg)
[deckerdence-cta-on-commbus-site.pdf](https://github.com/zeiq-co/commbus/files/4164190/deckerdence-cta-on-commbus-site.pdf)

![deckerdence-logo](https://user-images.githubusercontent.com/40568273/73922699-7fe7b100-48c1-11ea-9fdc-48769279d776.png)

**Comment by kpierduta** [comment]
Change hover on blog image 'read more' button to the dark grey instead of the different blue it is currently

<img width="255" alt="Screenshot 2020-02-06 09 21 18" src="https://user-images.githubusercontent.com/40568273/73923019-1916c780-48c2-11ea-96f1-7bd28a20ea3b.png">
