### ISSUE TITLE
'Main page' template change

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/commbus#43]
This applies to the promotional and event support page.

Put in a 3 image block underneath icon section that has the labels

Single deck - Double-deck - Open-top bus

then when the 3 block with bullets is, have that as projects instead.

(I will add a screenshot of design)

**Comment by iamkunall** [comment]
@kpierduta, please provide screenshot for this section

**Comment by kpierduta** [comment]
@iamkunall 
Screenshot  attached :)

[main-pages-template-page.pdf](https://github.com/zeiq-co/commbus/files/4121959/main-pages-template-page.pdf)

![main-pages-template-page](https://user-images.githubusercontent.com/40568273/73257680-1a5a3d00-41bc-11ea-8f81-5b030309b45a.png)
