### ISSUE TITLE
Changes and errors

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/commbus#46]
- [x] Can we filter the Case studies by date as well, the same as we do on the blogs, please

- [x] Can we change the formatting of text in this section (so it changes on all pages)

1. Change subtitle to Bebas - so that it is consistent with the other subtitles on the page (above)
2. Change paragraphs within the 3 columns to be the same formatting as other paragraphs on the page. So font format is consistent.

<img width="1226" alt="Screenshot 2020-03-23 16 18 51" src="https://user-images.githubusercontent.com/40568273/77339561-ddc24200-6d23-11ea-9d18-0d36c419443c.png">

- [x] On promotional buses and event support page in this section it is not showing the titles for the columns which are pulled from the image titles.

<img width="1242" alt="Screenshot 2020-03-23 16 37 03" src="https://user-images.githubusercontent.com/40568273/77340025-9be5cb80-6d24-11ea-9934-0c9d06966f53.png">

- [x] Can we add this section to all branding pages please underneath the hero section (Banner Graphics, Overlay Graphics, Full wrap, Simple Internal & Bespoke internal) - like it is currently on other pages I need to change the icons and text - which I will do after in Contentful.

<img width="1280" alt="Screenshot 2020-03-23 16 40 52" src="https://user-images.githubusercontent.com/40568273/77340395-23cbd580-6d25-11ea-938f-bef882bf31a4.png">

- [x] Privacy page, terms and conditions pages not displaying as formatted

<img width="1224" alt="Screenshot 2020-03-24 12 33 46" src="https://user-images.githubusercontent.com/40568273/77426142-d2c2ec80-6dcb-11ea-93aa-8d4ec6087d65.png">
<img width="783" alt="Screenshot 2020-03-24 12 33 52" src="https://user-images.githubusercontent.com/40568273/77426150-d6567380-6dcb-11ea-88d4-59433dacaa0e.png">

- [x] Can we have ability to hyperlink to email addresses e.g. mailto:clare.macleod@commbus.com 
<img width="754" alt="Screenshot 2020-03-24 12 37 32" src="https://user-images.githubusercontent.com/40568273/77426382-47962680-6dcc-11ea-83f3-252bbd4bd7f1.png">

- [x] Add more space between sections on this page - 3 times as much and have images display like home page hero does - so in full and touching the right edge of the page

<img width="1280" alt="Screenshot 2020-03-24 at 17 17 02" src="https://user-images.githubusercontent.com/40568273/77456594-5a702180-6df3-11ea-97a7-c56df3aceb0b.png">

**Comment by iamkunall** [comment]
@kpierduta  sorry kelly we don't have the ability to hyperlink to email addresses in contentful

**Comment by kpierduta** [comment]
Last item just needs to be done - triple the amount of space between sections on the page https://confident-stonebraker-2d361d.netlify.com/vehicle and make sure images touch right edge of page and are displayed in full

**Comment by kpierduta** [comment]
- [ ] Can we add a divider that's 20px of the blue colour between the footer and the Deckerdence block

<img width="1278" alt="Screenshot 2020-03-26 14 57 02" src="https://user-images.githubusercontent.com/40568273/77661081-1192a700-6f72-11ea-9eb5-fe3e00a29af5.png">

**Comment by kpierduta** [comment]
- [x] WE AIM TO REPLY TO YOUR ENQUIRY WITHIN 1 WORKING DAY. (take the S of DAYS)

Commbus
- [x] Blyth Hall Farm <<< take the e off that's on the website
Blythe Road
Coleshill

<img width="491" alt="Screenshot 2020-03-26 14 56 01" src="https://user-images.githubusercontent.com/40568273/77661471-954c9380-6f72-11ea-87c5-3bf31cd10aa8.png">

**Comment by kpierduta** [comment]
- [x] Can this just be one block of text so one column instead of 2 on the about page - https://confident-stonebraker-2d361d.netlify.com/about
- [x] Please make paragraph size consistent - so same as paragraph size from the hero paragraph text (Screenshot below)

<img width="1280" alt="Screenshot 2020-03-26 15 03 12" src="https://user-images.githubusercontent.com/40568273/77661830-0db35480-6f73-11ea-954b-6aca3fdc3b40.png">

<img width="845" alt="Screenshot 2020-03-26 15 05 56" src="https://user-images.githubusercontent.com/40568273/77662065-4e12d280-6f73-11ea-8b2b-95a23a07034c.png">

**Comment by kpierduta** [comment]
- [x] Please style all buttons across site like Zeplin. All capitals, Bebas 

Current:
<img width="231" alt="Screenshot 2020-03-30 09 55 00" src="https://user-images.githubusercontent.com/40568273/77894077-afd18600-726c-11ea-8778-fab89b6da0e5.png">

Zeplin:
<img width="302" alt="Screenshot 2020-03-30 09 55 53" src="https://user-images.githubusercontent.com/40568273/77894080-b06a1c80-726c-11ea-9da5-2e135da2a495.png">

**Comment by kpierduta** [comment]
- [x] On the forms can we have title on left-hand side back. So it says 'CONTACT US' on left-hand side and on the right-hand side it says 'QUICK FORM'

<img width="1279" alt="Screenshot 2020-03-30 09 58 12" src="https://user-images.githubusercontent.com/40568273/77894289-fc1cc600-726c-11ea-9beb-32b2ee324894.png">

Sorry I told the client it doesn't look right since they wanted the title on right and nothing on left
