### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/commbus#49]
- [x] https://www.commbus.com/eventsupport - the office on location link currently not working:
<img width="601" alt="Screenshot 2020-06-20 at 11 25 33" src="https://user-images.githubusercontent.com/40568273/85199620-e6a5be00-b2e8-11ea-9f24-72b87257b8a8.png">

- [x] Blog images on mobile aren't pulling through

- [x] Can this link be to the final deckerdence URL (instead of netlify) (on this page https://www.commbus.com/eventsupport) - so https://www.deckerdence.com
<img width="398" alt="Screenshot 2020-06-20 11 31 30" src="https://user-images.githubusercontent.com/40568273/85199723-ad218280-b2e9-11ea-9678-c735ef797a09.png">

- [x] On same page - remove link
<img width="404" alt="Screenshot 2020-06-20 11 32 42" src="https://user-images.githubusercontent.com/40568273/85199742-c6c2ca00-b2e9-11ea-90ab-7fc2771a45ec.png">

- [x] On same page - remove link
<img width="388" alt="Screenshot 2020-06-20 11 33 10" src="https://user-images.githubusercontent.com/40568273/85199753-d93d0380-b2e9-11ea-8071-88b33e326cc9.png">

- [x] on promotional buses page - remove the links from these sections
<img width="1208" alt="Screenshot 2020-06-21 13 27 50" src="https://user-images.githubusercontent.com/40568273/85224583-440e3d80-b3c3-11ea-98c7-a441e3656319.png">

- [x] On the contact page, is there any way we can either remove the writing that says Deckerdence in the map, or have it say Commbus?
<img width="226" alt="Screenshot 2020-06-21 13 30 51" src="https://user-images.githubusercontent.com/40568273/85224630-7d46ad80-b3c3-11ea-8d97-c87db7932a3a.png">

- [x] Can we add a 'RESET' to the categories on the case studies and news pages

**Comment by dharmveer97** [comment]
Hey @kpierduta how are you
- At order 22, and  6, and 4 news blogs mobile images empty in contentful. I just add existing mobile images. That's is why the site is not built by Netlify. Please check Order numbers 22, 6, and 4 I just add random images.
- On the office on the location link the slug (button link) in capital letters that's why page not open. Now I fixed please check.
