### ISSUE TITLE
Wordpress export of blog posts

### ISSUE THREAD

**Issue by kpierduta** [zeiq-co/commbus#9]
@perminder-klair will you be able to help with this along with making sure we retain all of the URLs that they currently sit on.

http://staging.commbus.com/wp-admin
UN: admin_kpdigital
PW: bA7P01cOmimF

**Comment by kpierduta** [comment]
@perminder-klair or do you need database access? Let me know :-)

**Comment by perminder-klair** [comment]
https://github.com/freeletics/wordpress-exporter
https://medium.com/swlh/how-to-migrate-your-site-from-wordpress-to-contentful-7512be5402bf
https://github.com/xdmorgan/wordpress-to-contentful
https://github.com/kmelve/wordpress-to-sanity/blob/master/src/migrate.js

https://www.staging.commbus.com/wp-admin
